# -*- coding: utf-8 -*-
"""Anjani_Lahoty_MoviesDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-6Tnj-hyEkygIYN-m2HjijV9i1YQlKd

Importing SQLite3 Module and Connecting to the Database and Creating a Database
"""

import sqlite3
connection = sqlite3.connect("movies.db")

"""Creating a cursor to execute queries and Creating a Table"""

cursor = connection.cursor()
cursor.execute(" CREATE TABLE movies (name TEXT, actor TEXT, actress TEXT, director TEXT, year INTEGER)")

"""Inserting Values into the Movies Table"""

cursor.execute("INSERT INTO movies VALUES('war','Hrithik','Vaani Kapoor','Siddharth',2019)")
cursor.execute("INSERT INTO movies VALUES('3 Idiots', 'Aamir Khan','Kareena Kapoor','RajKumar Hirani',2009)")
cursor.execute("INSERT INTO movies VALUES('Zero','SRK','katrina','Aanand',2018)")
cursor.execute("INSERT INTO movies VALUES('Sanju','Ranbir','Sonam','Rajkumar',2018)")
cursor.execute("INSERT INTO movies VALUES('Raees','SRK','Maahira','Rahul',2017)")

"""Reading Data from the Database and Simple SELECT statement to query all rows from the Movies table"""

rows = cursor.execute("SELECT * FROM movies").fetchall()
for i in rows:
  name,actor,actress,director,year = i
  print(name+"\t"+actor+"\t"+actress+"\t"+director+"\t"+str(year))

"""Query with parameter like actor name to select movies based on the actor's name."""

actor_rows = cursor.execute("SELECT * FROM movies WHERE actor='SRK'").fetchall()
for i in actor_rows:
  name,actor,actress,director,year = i
  print(name+"\t"+actor+"\t"+actress+"\t"+director+"\t"+str(year))